

trigger:
- main

pool:
  name: Agent15Apr

steps:
- task: TerraformTask@5
  displayName: terraform init
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/Dev/Root'
    backendServiceArm: 'awesome'
    backendAzureRmStorageAccountName: 'storagegauravssris'
    backendAzureRmContainerName: 'gauravbackuptfstate'
    backendAzureRmKey: 'backup.tfstate'