trigger:
- main

pool:
  name: FreshAgent

stages:

- stage: Terraform_Init
  displayName: Terraform Init Stage
  jobs:
  - job: Init
    steps:
    - task: TerraformTask@5
      displayName: Terraform Init
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/Root/Dev'
        backendServiceArm: 'FreshServiceConnection'
        backendAzureRmResourceGroupName: 'rg-terraform-state'
        backendAzureRmStorageAccountName: 'storagegauravssris'
        backendAzureRmContainerName: 'gauravbackuptfstate'
        backendAzureRmKey: 'backup.tfstate'
# PROD STAGE
- stage: Prod_Init
  displayName: Prod Terraform Init
  jobs:
  - job: InitProd
    steps:
    - task: TerraformTask@5
      displayName: Terraform Init Prod
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/Root/Prod'
        backendServiceArm: 'FreshServiceConnection'
        backendAzureRmResourceGroupName: 'rg-terraform-state'
        backendAzureRmStorageAccountName: 'storagegauravssris'
        backendAzureRmContainerName: 'gauravbackuptfstate'
        backendAzureRmKey: 'prod.tfstate'        