

trigger:
- main

pool:
  name: AgentMay

steps:
- 
- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/Root/Dev'
    backendServiceArm: 'awesome'
    backendAzureRmStorageAccountName: 'gauravstrg'
    backendAzureRmContainerName: 'gauravcont'
    backendAzureRmKey: 'backup.tfstate'
