
trigger:
- main

pool:
  name: AgentService

steps:
- task: TerraformTask@5
  displayName: Terraform Init
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/Root/Dev'
    backendServiceArm: 'newsc'
    backendAzureRmStorageAccountName: 'storagegauravssris'
    backendAzureRmContainerName: 'gauravbackuptfstate'
    backendAzureRmKey: 'backup.tfstate'
